/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/formCliente` | `/formCliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/formEntrenador` | `/formEntrenador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/newPassword` | `/newPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recoveryCode` | `/recoveryCode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recoveryPassword` | `/recoveryPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/splash` | `/splash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/formCliente` | `/formCliente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/formEntrenador` | `/formEntrenador`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/newPassword` | `/newPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/recoveryCode` | `/recoveryCode`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/recoveryPassword` | `/recoveryPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/splash` | `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/terms` | `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/config${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/formCliente${`?${string}` | `#${string}` | ''}` | `/formCliente${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/formEntrenador${`?${string}` | `#${string}` | ''}` | `/formEntrenador${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/newPassword${`?${string}` | `#${string}` | ''}` | `/newPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/recoveryCode${`?${string}` | `#${string}` | ''}` | `/recoveryCode${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/recoveryPassword${`?${string}` | `#${string}` | ''}` | `/recoveryPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/splash${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/terms${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/formCliente` | `/formCliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/formEntrenador` | `/formEntrenador`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/newPassword` | `/newPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recoveryCode` | `/recoveryCode`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/recoveryPassword` | `/recoveryPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/splash` | `/splash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
